baseurl = "/"
title = "Memento"
theme = "dimension"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Memento"
  description = '<!--[-->Un restaurant de qualité servant de la <a href="#menu">Fast Good</a><!--]--><br />
                <!--[-->au milieu du <a href="#intro">9 ème</a>.<!--]-->'
  logo = "fa-diamond"
  copyright = "Memento ++"


[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.fr]
languageName = "Français"
weight = 1
title = "Memento"

[languages.en]
languageName = "English"
weight = 2
title = "Memento"
description = '<!--[-->An awesome restaurant serving <a href="#menu">Fast Good</a><!--]--><br />
                <!--[-->in the middle of the <a href="#intro">9</a>.<!--]-->'
